# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
confirm_CJMLE_MIRTb_cpp <- function(response, nonmis_ind, theta0, A0, Q, C, tol) {
    .Call(`_biglfm_confirm_CJMLE_MIRTb_cpp`, response, nonmis_ind, theta0, A0, Q, C, tol)
}

#' @export
CJMLE_MIRT <- function(response, nonmis_ind, theta0, A0, Q, C, tol, parallel) {
    .Call(`_biglfm_CJMLE_MIRT`, response, nonmis_ind, theta0, A0, Q, C, tol, parallel)
}

#' @export
neg_loglik_linear <- function(thetaA, response, sigma_square) {
    .Call(`_biglfm_neg_loglik_linear`, thetaA, response, sigma_square)
}

#' @export
neg_loglik_linear_i_cpp <- function(response_i, A, theta_i, sigma_square) {
    .Call(`_biglfm_neg_loglik_linear_i_cpp`, response_i, A, theta_i, sigma_square)
}

#' @export
grad_neg_loglik_linear_thetai_cpp <- function(response_i, A, theta_i, sigma_square) {
    .Call(`_biglfm_grad_neg_loglik_linear_thetai_cpp`, response_i, A, theta_i, sigma_square)
}

#' @export
Update_theta_linear_cpp <- function(theta0, response, A0, sigma_square, C) {
    .Call(`_biglfm_Update_theta_linear_cpp`, theta0, response, A0, sigma_square, C)
}

#' @export
neg_loglik_linear_j_cpp <- function(response_j, A_j, theta, sigma_square) {
    .Call(`_biglfm_neg_loglik_linear_j_cpp`, response_j, A_j, theta, sigma_square)
}

#' @export
grad_neg_loglik_linear_A_j_cpp <- function(response_j, A_j, Q_j, theta, sigma_square) {
    .Call(`_biglfm_grad_neg_loglik_linear_A_j_cpp`, response_j, A_j, Q_j, theta, sigma_square)
}

#' @export
Update_A_linear_cpp <- function(A0, Q, response, theta1, sigma_square, C) {
    .Call(`_biglfm_Update_A_linear_cpp`, A0, Q, response, theta1, sigma_square, C)
}

#' @export
CJMLE_linear <- function(response, theta0, A0, Q, sigma_square, C, tol, parallel) {
    .Call(`_biglfm_CJMLE_linear`, response, theta0, A0, Q, sigma_square, C, tol, parallel)
}

#' @export
CJMLE_poisson <- function(response, theta0, A0, Q, C, tol, parallel) {
    .Call(`_biglfm_CJMLE_poisson`, response, theta0, A0, Q, C, tol, parallel)
}

prox_func_cpp <- function(y, C) {
    .Call(`_biglfm_prox_func_cpp`, y, C)
}

#' @export
myKendall_cpp <- function(x, y) {
    .Call(`_biglfm_myKendall_cpp`, x, y)
}

#' @export
sample_A_func <- function(K, J, C, frac) {
    .Call(`_biglfm_sample_A_func`, K, J, C, frac)
}

#' @export
sample_theta_func <- function(K, N, C, frac) {
    .Call(`_biglfm_sample_theta_func`, K, N, C, frac)
}

